version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi_starter
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  api-tests:
    build:
      context: .
      target: test
    environment:
      ENVIRONMENT: test
      TEST_DB_HOST: db
    depends_on:
      - db  
    networks:
      - app-network
    volumes:
      - ./report:/app/report

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 